---
abstract: 'Generate POD documentation for a package from Rinci metadata'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.001, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-To-POD
requires:
  File::Which: 0
  Locale::Maketext::Lexicon::Gettext: 0
  Log::Any: 0
  Markdown::Pod: 0
  Moo: 0
  Perinci::Access: 0
  Perinci::CmdLine: 0.80
  Perinci::Sub::To::POD: 0.07
  Perinci::Sub::Util: 0
  Perinci::To::PackageBase: 0.27
  Perinci::To::PackageBase::I18N: 0.27
  Perinci::To::PackageBase::I18N::en: 0.27
  Perinci::To::Text: 0.27
  Riap: v1.1.8
  Rinci: v1.1.36
  perl: 5.010001
resources: {}
version: 0.37
